function ContextOpen()
        LocalPlayer():ConCommand ("open_context_menu")
end
hook.Add ("OnContextMenuOpen", "Context", ContextOpen)

function closecontext ()
        if loz then
                loz:Remove()
        end
end
hook.Add ("OnContextMenuClose", "Context", closecontext)

function draw_textbox(strTitle, strBtn, strDefaultText, fnEnter)
        local Window = vgui.Create ("DFrame")
        Window:SetTitle (strTitle)
        Window:ShowCloseButton(true)
        Window:MakePopup()
        Window:SetSize (250, 100)
        Window:Center()
        Window:SetKeyboardInputEnabled(true)
        Window:SetMouseInputEnabled(true)
        Window.Paint = function()
                draw.RoundedBox ( 0, 0, 0, Window:GetWide(), Window:GetTall(), Color(0,0,0,255) )
                draw.RoundedBox ( 0, 1, 1, Window:GetWide()-2, Window:GetTall()-2, Color(255,255,255,100) )
        end

        local TextEntr = vgui.Create( "DTextEntry", Window)
        TextEntr:SetPos (75, 25)
        TextEntr:SetSize (110, 20)
        TextEntr:SetMultiline (false)
        TextEntr:SetAllowNonAsciiCharacters( true )
        TextEntr:SetText(strDefaultText || "")
        TextEntr:SetEnterAllowed (true)

        local Btn = vgui.Create ("DButton", Window)
        Btn:SetText(strBtn)
        Btn:SetSize (110, 20)
        Btn:SetPos (75, 50)
        Btn.DoClick = function ()
                fnEnter( TextEntr:GetValue() )
                Window:Remove()
        end
end

function OpenContextMenu(ply, argm, cmd)
        local context = DermaMenu()
		if ply:getJobTable().isOTA then
		local otacod, editota = context:AddSubMenu("Коды")
		otacod:AddOption( "Выполняю", function() RunConsoleCommand ("say", "выполняю") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Есть", function() RunConsoleCommand ("say", "есть") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Есть попадание", function() RunConsoleCommand ("say", "есть попадание") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Внимание", function() RunConsoleCommand ("say", "внимание") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Нарушитель один", function() RunConsoleCommand ("say", "враг один") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Дезинфекция", function() RunConsoleCommand ("say", "дезинфекция") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Аспект", function() RunConsoleCommand ("say", "аспект") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Азимут", function() RunConsoleCommand ("say", "азимут") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Ложись", function() RunConsoleCommand ("say", "ложись") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Вижу паразита", function() RunConsoleCommand ("say", "вижу паразита") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Возможно цель номер один", function() RunConsoleCommand ("say", "вероятно Фримен") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Чисто", function() RunConsoleCommand ("say", "чисто") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Опасная форма жизни", function() RunConsoleCommand ("say", "опасная форма жизни") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Чёрт", function() RunConsoleCommand ("say", "чёрт") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Контакт", function() RunConsoleCommand ("say", "контакт") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Есть контакт", function() RunConsoleCommand ("say", "есть контакт") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Есть контакт преследую", function() RunConsoleCommand ("say", "преследую контакт") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Убит", function() RunConsoleCommand ("say", "убит") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Продолжаю задержание", function() RunConsoleCommand ("say", "продолжаю задержание") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Вас понял", function() RunConsoleCommand ("say", "вас понял") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Прикрой", function() RunConsoleCommand ("say", "прикрой") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Прикрой своих", function() RunConsoleCommand ("say", "своих прикрой") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Градусов", function() RunConsoleCommand ("say", "градусов") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Готов", function() RunConsoleCommand ("say", "готов") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Цель обозначена", function() RunConsoleCommand ("say", "обозначена цель") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Уходим", function() RunConsoleCommand ("say", "уходим") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "8", function() RunConsoleCommand ("say", "8") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "18", function() RunConsoleCommand ("say", "18") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "80", function() RunConsoleCommand ("say", "8-0") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "11", function() RunConsoleCommand ("say", "11") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Продолжаю зачистку", function() RunConsoleCommand ("say", "продолжаю зачистку") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Работаю", function() RunConsoleCommand ("say", "работаю") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Веду преследование", function() RunConsoleCommand ("say", "веду преследование") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Пошла граната", function() RunConsoleCommand ("say", "пошла граната") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Внимание граната", function() RunConsoleCommand ("say", "внимание граната") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "15", function() RunConsoleCommand ("say", "1.5") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "50", function() RunConsoleCommand ("say", "5.0") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "5", function() RunConsoleCommand ("say", "5") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Граната", function() RunConsoleCommand ("say", "граната") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "4", function() RunConsoleCommand ("say", "4") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "14", function() RunConsoleCommand ("say", "1.4") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "40", function() RunConsoleCommand ("say", "4.0") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Фримен", function() RunConsoleCommand ("say", "Фримен") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Цель видна", function() RunConsoleCommand ("say", "цель видна") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Вижу цель", function() RunConsoleCommand ("say", "вижу цель") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Держать позиции", function() RunConsoleCommand ("say", "держать позиции") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Запрашиваю Центр у нас проблемы", function() RunConsoleCommand ("say", "повстанцы") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Заражён", function() RunConsoleCommand ("say", "заражён") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Назначен командиром Один в отряде", function() RunConsoleCommand ("say", "назначен командир") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Отряд уничтожен требую подкрепления", function() RunConsoleCommand ("say", "отряд уничтожен") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Цель не вижу", function() RunConsoleCommand ("say", "не вижу цель") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Движение проверить сектора", function() RunConsoleCommand ("say", "движение проверить сектора") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Вперёд", function() RunConsoleCommand ("say", "вперёд") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Нежить", function() RunConsoleCommand ("say", "нежить") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "9", function() RunConsoleCommand ("say", "9") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "19", function() RunConsoleCommand ("say", "1.9") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "90", function() RunConsoleCommand ("say", "9.0") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Нейтрализован", function() RunConsoleCommand ("say", "нейтрализован") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Погиб на посту", function() RunConsoleCommand ("say", "погиб на посту") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "100", function() RunConsoleCommand ("say", "100") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Мятеж", function() RunConsoleCommand ("say", "мятеж") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Центр", function() RunConsoleCommand ("say", "центр") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Центр прошу поддержки резерва", function() RunConsoleCommand ("say", "поддержка резерва") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Центр прошу воздушной поддержки", function() RunConsoleCommand ("say", "воздушная поддержка") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Сектор захвачен", function() RunConsoleCommand ("say", "сектор захвачен") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Цель номер один уничтожена", function() RunConsoleCommand ("say", "Фримен убит") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Цель уничтожена", function() RunConsoleCommand ("say", "танго уничтожена") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Центр рота уничтожена", function() RunConsoleCommand ("say", "рота уничтожена") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Цель номер один", function() RunConsoleCommand ("say", "цель номер один") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Бронепехотные отряды", function() RunConsoleCommand ("say", "бронетехника") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Сдерживание", function() RunConsoleCommand ("say", "сдерживание") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Ranger", function() RunConsoleCommand ("say", "ranger") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "STATUS:ORANGE", function() RunConsoleCommand ("say", "код 2") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Оружие к бою", function() RunConsoleCommand ("say", "оружие") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Статус", function() RunConsoleCommand ("say", "статус") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "STATUS:GREEN", function() RunConsoleCommand ("say", "код 4") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Требуется медпомощь", function() RunConsoleCommand ("say", "Требуется медпомощь") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Зона блокирована", function() RunConsoleCommand ("say", "ограничено") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Сектор", function() RunConsoleCommand ("say", "сектор") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "В секторе опасность", function() RunConsoleCommand ("say", "опасность в секторе") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Сектор чист", function() RunConsoleCommand ("say", "зона чиста") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Зона заражения", function() RunConsoleCommand ("say", "зона заражения") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "7", function() RunConsoleCommand ("say", "7") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "17", function() RunConsoleCommand ("say", "1.7") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "70", function() RunConsoleCommand ("say", "7.0") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "6", function() RunConsoleCommand ("say", "6") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "16", function() RunConsoleCommand ("say", "1.6") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "60", function() RunConsoleCommand ("say", "6.0") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Жду указаний", function() RunConsoleCommand ("say", "жду указаний") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Внимательно", function() RunConsoleCommand ("say", "внимательно") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Выдвигаюсь", function() RunConsoleCommand ("say", "Выдвигаюсь") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Цель пропала, прочесать местность", function() RunConsoleCommand ("say", "цель пропала") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Цель поражена", function() RunConsoleCommand ("say", "цель поражена") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Рота готова, прочёсываем", function() RunConsoleCommand ("say", "рота готова") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "Легко ранен", function() RunConsoleCommand ("say", "легко ранен") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "10", function() RunConsoleCommand ("say", "10") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "13", function() RunConsoleCommand ("say", "1.3") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "33", function() RunConsoleCommand ("say", "3.3") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "3", function() RunConsoleCommand ("say", "3") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "300", function() RunConsoleCommand ("say", "300") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "20", function() RunConsoleCommand ("say", "2.0") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "2", function() RunConsoleCommand ("say", "2") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "200", function() RunConsoleCommand ("say", "200") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "На подходе", function() RunConsoleCommand ("say", "на подходе") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "У нас здесь паразиты", function() RunConsoleCommand ("say", "у нас здесь паразиты") end):SetImage("icon16/user_comment.png")
otacod:AddOption( "0", function() RunConsoleCommand ("say", "0") end):SetImage("icon16/user_comment.png")
end

		if (ply:Team() == TEAM_VORTI) or (ply:Team() == TEAM_VORTIGOT) then
		 local vortmenucod, editvort = context:AddSubMenu("Общение")
            editvort:SetImage ("icon16/heart.png")
			vortmenucod:AddOption( "Да", function() RunConsoleCommand ("say", "да") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Нет", function() RunConsoleCommand ("say", "нет") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Мы потеряли всё, что было нам дорого", function() RunConsoleCommand ("say", "Мы потеряли всё , что было нам дорого") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Внимание", function() RunConsoleCommand ("say", "внимание") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Готово", function() RunConsoleCommand ("say", "готово") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Всё", function() RunConsoleCommand ("say", "всё") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Мы боимся, что подвели тебя", function() RunConsoleCommand ("say", "Мы боимся, что подвели тебя") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Позволь мне", function() RunConsoleCommand ("say", "позволь мне") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Дай нам силу!", function() RunConsoleCommand ("say", "дай нам силу") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Ты можешь использовать это", function() RunConsoleCommand ("say", "Ты можешь использовать это") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Возьми", function() RunConsoleCommand ("say", "возьми") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Прибыли", function() RunConsoleCommand ("say", "прибыли") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Стой", function() RunConsoleCommand ("say", "стой") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "С честью мы идём за тобой", function() RunConsoleCommand ("say", "С честью мы идём за тобой") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Не двигайся, иначе не сможем помочь", function() RunConsoleCommand ("say", "не двигайся, иначе не сможем помочь") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Это ты, Фриман", function() RunConsoleCommand ("say", "Это ты, Фриман") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Какая честь", function() RunConsoleCommand ("say", "Какая честь") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Это Фриман", function() RunConsoleCommand ("say", "это Фриман") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Веди", function() RunConsoleCommand ("say", "веди") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "У нас одна цель", function() RunConsoleCommand ("say", "У нас одна цель") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Мы служим одной тайне", function() RunConsoleCommand ("say", "Мы служим одной тайне") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Мы не можем читать твои оптические ячейки", function() RunConsoleCommand ("say", "Мы не можем читать твои оптические ячейки") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Клянусь честью", function() RunConsoleCommand ("say", "клянусь честью") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Наше место здесь", function() RunConsoleCommand ("say", "Наше место здесь") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Готовься получить энергию", function() RunConsoleCommand ("say", "готовься получить энергию") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Удовлетворение", function() RunConsoleCommand ("say", "удовлетворение") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Отойди", function() RunConsoleCommand ("say", "отойди") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Мы еще здесь", function() RunConsoleCommand ("say", "Мы еще здесь") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Мы не убеждены", function() RunConsoleCommand ("say", "Мы не убеждены") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Ты не первый, кто испытывает иллюзии", function() RunConsoleCommand ("say", "Ты не первый, кто испытывает иллюзии") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Мы верим в обратное", function() RunConsoleCommand ("say", "Мы верим в обратное") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Тем лучше", function() RunConsoleCommand ("say", "Тем лучше") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Мы ожидали этого", function() RunConsoleCommand ("say", "Мы ожидали этого") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Пустые размышления", function() RunConsoleCommand ("say", "Пустые размышления") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Твоя забота трогательна", function() RunConsoleCommand ("say", "Твоя забота трогательна") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Ничего не предполагай", function() RunConsoleCommand ("say", "Ничего не предполагай") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "И не надейся", function() RunConsoleCommand ("say", "И не надейся") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Ты заблуждаешся", function() RunConsoleCommand ("say", "Ты заблуждаешся") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Надеемся, ты прав", function() RunConsoleCommand ("say", "Надеемся, ты прав") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Прости нас за вортигрубость", function() RunConsoleCommand ("say", "прости нас за вортигрубость") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Будь бдителен", function() RunConsoleCommand ("say", "Будь бдителен") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Мы тоже уверены", function() RunConsoleCommand ("say", "Мы тоже уверены") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Это чувство взаимно", function() RunConsoleCommand ("say", "Это чувство взаимно") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Это не привычно", function() RunConsoleCommand ("say", "Это не привычно") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Мы все часть множества", function() RunConsoleCommand ("say", "Мы все часть множества") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Между нами нет растояния", function() RunConsoleCommand ("say", "Между нами нет растояния") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Лонкх", function() RunConsoleCommand ("say", "лонг кх") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Гонго", function() RunConsoleCommand ("say", "гонго") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Галанга", function() RunConsoleCommand ("say", "галанга") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Галалум", function() RunConsoleCommand ("say", "галалум") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Чага лин, чага галагум", function() RunConsoleCommand ("say", "Чага лин, чага галагум") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Чала гон, чала гор", function() RunConsoleCommand ("say", "Чала гон, чала гор") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Мы потеряли всё, что дорого нам", function() RunConsoleCommand ("say", "Мы потеряли всё, что дорого нам") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Альянс заплатит за порочность", function() RunConsoleCommand ("say", "Альянс заплатит за порочность") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Надежка близка", function() RunConsoleCommand ("say", "надежда близка") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Это поворотный момент", function() RunConsoleCommand ("say", "Это поворотный момент") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Такой пессимизм обречет всех", function() RunConsoleCommand ("say", "Такой пессимизм обречет всех") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Мы пережили времена темнее", function() RunConsoleCommand ("say", "Мы пережили времена темнее") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Мы помним слова великого философа", function() RunConsoleCommand ("say", "Мы помним слова великого философа") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Наше сотрудничество осуждают", function() RunConsoleCommand ("say", "Наше сотрудничество осуждают") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Берегись", function() RunConsoleCommand ("say", "берегись") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Hады встрече", function() RunConsoleCommand ("say", "Мы рады встрече") end):SetImage("icon16/user_comment.png")
			vortmenucod:AddOption( "Мы жили и в худшие времена", function() RunConsoleCommand ("say", "Мы жили и в худшие времена") end):SetImage("icon16/user_comment.png")
		end
		  if not (ply:Team() == TEAM_MAYOR) and not (ply:Team() == TEAM_ZAM) and ply:isCP() and not ply:getJobTable().isOTA then

            local demotemenucod, editedcod = context:AddSubMenu("Статус-коды")
            editedcod:SetImage ("icon16/transmit_blue.png")

            demotemenucod:AddOption( "[КОД 1] Всем постам код 1, поддерживать командный пункт (Выносить приговор по усмотрению, тревога)", function() RunConsoleCommand ("broadcode", "КОД 1 [Всем постам код 1, поддерживать командный пункт]") end):SetImage("icon16/user_comment.png")
            demotemenucod:AddOption( "[КОД 2] Всем постам код 2 (Оружие в руках, приготовиться к сдерживанию!)", function() RunConsoleCommand ("broadcode", "КОД 2 [Всем постам код 2 (Оружие в руках, приготовиться к сдерживанию!)]") end):SetImage("icon16/user_comment.png")
            demotemenucod:AddOption( "[КОД 3] Отрядам поддержки код 3 (Опасность не подтверждена, ожидайте!)", function() RunConsoleCommand ("broadcode", "КОД 3 [Отрядам поддержки код 3 (Опасность не подтверждена, ожидайте!)]") end):SetImage("icon16/user_comment.png")
            demotemenucod:AddOption( "[КОД 3 и 4] У нас 3 и 4", function() RunConsoleCommand ("broadcode", "КОД 34") end):SetImage("icon16/user_comment.png")
            demotemenucod:AddOption( "[КОД 4] Ситуация под контролем, отбой тревоге", function() RunConsoleCommand ("broadcode", "КОД 4 [Ситуация под контролем, отбой тревоге]") end):SetImage("icon16/user_comment.png")
            demotemenucod:AddOption( "[КОД 4A] Ситуация не под контролем, сотрудники прибыли на место", function() RunConsoleCommand ("broadcode", "КОД 4 A [Ситуация не под контролем, сотрудники прибыли на место]") end):SetImage("icon16/user_comment.png")
            demotemenucod:AddOption( "[КОД 4N] Подкрепления не требуются, доказательств преступления не найдено", function() RunConsoleCommand ("broadcode", "КОД 4 N [Подкрепления не требуются, доказательств преступления не найдено]") end):SetImage("icon16/user_comment.png")
            demotemenucod:AddOption( "[КОД 5] Ведётся слежка", function() RunConsoleCommand ("broadcode", "КОД 5 [Ведётся слежка]") end):SetImage("icon16/user_comment.png")
            demotemenucod:AddOption( "[КОД 7] Покинул службу", function() RunConsoleCommand ("broadcode", "КОД 7 [Покинул службу]") end):SetImage("icon16/user_comment.png")
            demotemenucod:AddOption( "[КОД 10 0] Виновен в вооруженном нападении", function() RunConsoleCommand ("broadcode", "КОД 10 0 [Виновен в вооруженном нападении]") end):SetImage("icon16/user_comment.png")
            demotemenucod:AddOption( "[КОД 12] Вернуться к патрулированию", function() RunConsoleCommand ("broadcode", "КОД 12 [Вернуться к патрулированию]") end):SetImage("icon16/user_comment.png")
            demotemenucod:AddOption( "[КОД 77] Возможно засада", function() RunConsoleCommand ("broadcode", "КОД 77 [Возможно засада]") end):SetImage("icon16/user_comment.png")
            demotemenucod:AddOption( "[КОД 100] Все чисто", function() RunConsoleCommand ("broadcode", "КОД 100 [Все чисто]") end):SetImage("icon16/user_comment.png")


            local demotemenuoutcod, editedoutcod = context:AddSubMenu("Прочие коды")
            editedoutcod:SetImage ("icon16/transmit_blue.png")

            demotemenuoutcod:AddOption( "[КОД 63] Причинение вреда", function() RunConsoleCommand ("broadcode", "КОД 63 [Причинение вреда]") end):SetImage("icon16/user_comment.png")
            demotemenuoutcod:AddOption( "[КОД 69] Акты сексуального характера", function() RunConsoleCommand ("broadcode", "КОД 69 [Акты сексуального характера]") end):SetImage("icon16/user_comment.png")
            demotemenuoutcod:AddOption( "[КОД 69A] Попытка размножения", function() RunConsoleCommand ("broadcode", "КОД 69 A [Попытка размножения]") end):SetImage("icon16/user_comment.png")
            demotemenuoutcod:AddOption( "[КОД 187] Убийство", function() RunConsoleCommand ("broadcode", "КОД 187 [Убийство]") end):SetImage("icon16/user_comment.png")
            demotemenuoutcod:AddOption( "[КОД 211] Ограбление", function() RunConsoleCommand ("broadcode", "КОД 211 [Ограбление]") end):SetImage("icon16/user_comment.png")
            demotemenuoutcod:AddOption( "[КОД 211А] Попытка ограбления", function() RunConsoleCommand ("broadcode", "КОД 211 А [Попытка ограбления]") end):SetImage("icon16/user_comment.png")
            demotemenuoutcod:AddOption( "[КОД 245] Нападение с летальным исходом", function() RunConsoleCommand ("broadcode", "КОД 245 [Нападение с летальным исходом]") end):SetImage("icon16/user_comment.png")
            demotemenuoutcod:AddOption( "[КОД 404] Нарушитель", function() RunConsoleCommand ("broadcode", "КОД 404 [Нарушитель]") end):SetImage("icon16/user_comment.png")
            demotemenuoutcod:AddOption( "[КОД 415] Нарушение общественного порядка", function() RunConsoleCommand ("broadcode", "КОД 415 [Нарушение общественного порядка]") end):SetImage("icon16/user_comment.png")
            demotemenuoutcod:AddOption( "[КОД 505] Объект вооружен огнестрельным оружием", function() RunConsoleCommand ("broadcode", "КОД 505 [Объект вооружен огнестрельным оружием]") end):SetImage("icon16/user_comment.png")
            demotemenuoutcod:AddOption( "[КОД 505М] Объект вооружен оружием ближнего боя", function() RunConsoleCommand ("broadcode", "КОД 505 М [Объект вооружен оружием ближнего боя]") end):SetImage("icon16/user_comment.png")
            demotemenuoutcod:AddOption( "[КОД 505S] Выстрелы", function() RunConsoleCommand ("broadcode", "КОД 505 S [Выстрелы]") end):SetImage("icon16/user_comment.png")
            demotemenuoutcod:AddOption( "[КОД 594] Вандализм", function() RunConsoleCommand ("broadcode", "КОД 594 [Вандализм]") end):SetImage("icon16/user_comment.png")
            demotemenuoutcod:AddOption( "[КОД 904] Самоубийство", function() RunConsoleCommand ("broadcode", "КОД 904 [Самоубийство]") end):SetImage("icon16/user_comment.png")
            demotemenuoutcod:AddOption( "[КОД 904А] Самоубийство", function() RunConsoleCommand ("broadcode", "КОД 904 А [Попытка самоубийства]") end):SetImage("icon16/user_comment.png")
            demotemenuoutcod:AddOption( "[КОД 996] Взрыв", function() RunConsoleCommand ("broadcode", "КОД 996 [Взрыв]") end):SetImage("icon16/user_comment.png")
            demotemenuoutcod:AddOption( "[КОД 996В] Взрывное устройство", function() RunConsoleCommand ("broadcode", "КОД 996 B [Взрывное устройство]") end):SetImage("icon16/user_comment.png")
            demotemenuoutcod:AddOption( "[КОД 996Т] Угроза взрыва", function() RunConsoleCommand ("broadcode", "КОД 996 Т [Угроза взрыва]") end):SetImage("icon16/user_comment.png")


            local demotemenuorders, editedorders = context:AddSubMenu("Приказы")
            editedorders:SetImage ("icon16/transmit_blue.png")

            demotemenuorders:AddOption( "Применить", function() RunConsoleCommand ("say", "Применить") end):SetImage("icon16/user_comment.png")
            demotemenuorders:AddOption( "Отсечь", function() RunConsoleCommand ("say", "Отсечь") end):SetImage("icon16/user_comment.png")
            demotemenuorders:AddOption( "Стерелизовать", function() RunConsoleCommand ("say", "Стерелизовать") end):SetImage("icon16/user_comment.png")
            demotemenuorders:AddOption( "Нарушитель", function() RunConsoleCommand ("say", "Нарушитель") end):SetImage("icon16/user_comment.png")
            demotemenuorders:AddOption( "Гражданин", function() RunConsoleCommand ("say", "Гражданин") end):SetImage("icon16/user_comment.png")
            demotemenuorders:AddOption( "Применить", function() RunConsoleCommand ("say", "Применить") end):SetImage("icon16/user_comment.png")
            demotemenuorders:AddOption( "Выполнять", function() RunConsoleCommand ("say", "Выполнять") end):SetImage("icon16/user_comment.png")
            demotemenuorders:AddOption( "Доложить на КП", function() RunConsoleCommand ("say", "Доложить на КП") end):SetImage("icon16/user_comment.png")

            demotemenuorders:AddOption( "", function() end)
            demotemenuorders:AddOption( "Стоять", function() RunConsoleCommand ("say", "Стоять") end):SetImage("icon16/user_comment.png")
            demotemenuorders:AddOption( "Документ", function() RunConsoleCommand ("say", "Документ") end):SetImage("icon16/user_comment.png")
            demotemenuorders:AddOption( "Двигайся", function() RunConsoleCommand ("say", "Двигайся") end):SetImage("icon16/user_comment.png")
            demotemenuorders:AddOption( "Назад", function() RunConsoleCommand ("say", "Назад") end):SetImage("icon16/user_comment.png")
            demotemenuorders:AddOption( "Я сказал отойти", function() RunConsoleCommand ("say", "Я сказал отойти") end):SetImage("icon16/user_comment.png")
            demotemenuorders:AddOption( "Проверить", function() RunConsoleCommand ("say", "Проверить") end):SetImage("icon16/user_comment.png")
            demotemenuorders:AddOption( "Стоять на месте", function() RunConsoleCommand ("say", "Стоять на месте") end):SetImage("icon16/user_comment.png")
            demotemenuorders:AddOption( "Можешь идти", function() RunConsoleCommand ("say", "можешь идти") end):SetImage("icon16/user_comment.png")
            demotemenuorders:AddOption( "", function() end)
            demotemenuorders:AddOption( "Первое предупреждение", function() RunConsoleCommand ("say", "Первое предупреждение") end):SetImage("icon16/user_comment.png")
            demotemenuorders:AddOption( "Второе предупреждение", function() RunConsoleCommand ("say", "Второе предупреждение") end):SetImage("icon16/user_comment.png")
            demotemenuorders:AddOption( "Последнее предупреждение", function() RunConsoleCommand ("say", "Последнее предупреждение") end):SetImage("icon16/user_comment.png")
            demotemenuorders:AddOption( "", function() end)
            demotemenuorders:AddOption( "Проверка лояльности", function() RunConsoleCommand ("say", "Проверка лояльности") end):SetImage("icon16/user_comment.png")
            demotemenuorders:AddOption( "Не прошел проверку лояльности", function() RunConsoleCommand ("say", "Не прошел проверку лояльности") end):SetImage("icon16/user_comment.png")
            demotemenuorders:AddOption( "", function() end)
            demotemenuorders:AddOption( "Изолировать", function() RunConsoleCommand ("say", "Изолировать") end):SetImage("icon16/user_comment.png")
            demotemenuorders:AddOption( "Фиксировать", function() RunConsoleCommand ("say", "Фиксировать") end):SetImage("icon16/user_comment.png")
            demotemenuorders:AddOption( "Продолжаю поиск", function() RunConsoleCommand ("say", "Продолжаю поиск") end):SetImage("icon16/user_comment.png")
            demotemenuorders:AddOption( "Следите за показаниями на радаре", function() RunConsoleCommand ("say", "Следите за показаниями на радаре") end):SetImage("icon16/user_comment.png")
            demotemenuorders:AddOption( "Выйти к назначенным точкам", function() RunConsoleCommand ("say", "Выйти к назначенным точкам") end):SetImage("icon16/user_comment.png")


            local demotemenusay, editedsay = context:AddSubMenu("Общение")
            editedsay:SetImage ("icon16/transmit_blue.png")

            demotemenusay:AddOption( "*Смех*", function() RunConsoleCommand ("say", "хаха") end):SetImage("icon16/user_comment.png")
            demotemenusay:AddOption( "Вижу его", function() RunConsoleCommand ("say", "Вижу его") end):SetImage("icon16/user_comment.png")
            demotemenusay:AddOption( "Есть", function() RunConsoleCommand ("say", "Есть") end):SetImage("icon16/user_comment.png")
            demotemenusay:AddOption( "Понял", function() RunConsoleCommand ("say", "Понял") end):SetImage("icon16/user_comment.png")
            demotemenusay:AddOption( "Всем выдвигаться", function() RunConsoleCommand ("say", "Всем выдвигаться") end):SetImage("icon16/user_comment.png")
            demotemenusay:AddOption( "Докладывать передвижение подозреваемого", function() RunConsoleCommand ("say", "Докладывать передвижение подозреваемого") end):SetImage("icon16/user_comment.png")
            demotemenusay:AddOption( "На точке", function() RunConsoleCommand ("say", "На точке") end):SetImage("icon16/user_comment.png")
            demotemenusay:AddOption( "Канал", function() RunConsoleCommand ("say", "Канал") end):SetImage("icon16/user_comment.png")
            demotemenusay:AddOption( "Докладываю о призванном", function() RunConsoleCommand ("say", "Докладываю о призванном") end):SetImage("icon16/user_comment.png")
            demotemenusay:AddOption( "Смерть объекта", function() RunConsoleCommand ("say", "Смерть объекта") end):SetImage("icon16/user_comment.png")
            demotemenusay:AddOption( "Убита", function() RunConsoleCommand ("say", "Убита") end):SetImage("icon16/user_comment.png")
            demotemenusay:AddOption( "Пункт под угрозой", function() RunConsoleCommand ("say", "Пункт под угрозой") end):SetImage("icon16/user_comment.png")
            demotemenusay:AddOption( "Предположительно нападение", function() RunConsoleCommand ("say", "Предположительно нападение") end):SetImage("icon16/user_comment.png")
            demotemenusay:AddOption( "Приговор приведен в исполнение", function() RunConsoleCommand ("say", "Приговор приведен в исполнение") end):SetImage("icon16/user_comment.png")
            demotemenusay:AddOption( "Есть 1 сообщник", function() RunConsoleCommand ("say", "есть 1 Сообщник") end):SetImage("icon16/user_comment.png")
            demotemenusay:AddOption( "Ввести", function() RunConsoleCommand ("say", "Ввести") end):SetImage("icon16/user_comment.png")
            demotemenusay:AddOption( "Есть попадание", function() RunConsoleCommand ("say", "Есть попадание") end):SetImage("icon16/user_comment.png")
            demotemenusay:AddOption( "Воздух", function() RunConsoleCommand ("say", "Воздух") end):SetImage("icon16/user_comment.png")
            demotemenusay:AddOption( "Злоумышленник", function() RunConsoleCommand ("say", "Злоумышленник") end):SetImage("icon16/user_comment.png")
            demotemenusay:AddOption( "Помощь нужна?", function() RunConsoleCommand ("say", "Помощь нужна ?") end):SetImage("icon16/user_comment.png")
            demotemenusay:AddOption( "Патруль", function() RunConsoleCommand ("say", "Патруль") end):SetImage("icon16/user_comment.png")
            demotemenusay:AddOption( "Закрытый", function() RunConsoleCommand ("say", "Закрытый") end):SetImage("icon16/user_comment.png")
            demotemenusay:AddOption( "Чёрт", function() RunConsoleCommand ("say", "Чёрт") end):SetImage("icon16/user_comment.png")
            demotemenusay:AddOption( "Ты её перевернул подними", function() RunConsoleCommand ("say", "Ты её перевернул подними") end):SetImage("icon16/user_comment.png")
            demotemenusay:AddOption( "Союз", function() RunConsoleCommand ("say", "Союз") end):SetImage("icon16/user_comment.png")
            context:AddSpacer()context:AddSpacer()
			end


        if ply:isCP() then
                local submenu, edit = context:AddSubMenu ("Обьявить розыск")
                edit:SetImage ("icon16/medal_bronze_1.png")
                for _,v in pairs (player.GetAll()) do
                        if v != LocalPlayer() then
                                submenu:AddOption (v:Name(), function()
                                        draw_textbox("Введите причину для розыска", "Объявить в розыск", "", function(a) RunConsoleCommand ("darkrp", "wanted" ,v:Name(), tostring(a)) end)
                                end):SetImage("icon16/user.png")
                        end
                end
				local unwanted, unwanted2 = context:AddSubMenu("Снять Розыск")
                unwanted2:SetImage ("icon16/medal_bronze_delete.png")
                for _,v in pairs (player.GetAll()) do
                        if v != LocalPlayer() then
                                unwanted:AddOption (v:Name(), function()
                                        RunConsoleCommand ("darkrp", "unwanted", v:Name())
                                end):SetImage ("icon16/user.png")
                        end
                end

local demotemenu, edited = context:AddSubMenu("Уволить игрока")
                edited:SetImage ("icon16/error_delete.png")
                for _,v in pairs (player.GetAll()) do
                        if v != LocalPlayer() then
                                demotemenu:AddOption (v:Name(), function ()
                                        draw_textbox("Введите причину увольнения", "Уволить", "", function(a) RunConsoleCommand ("darkrp", "demote", v:Name(), tostring(a)) end)
                                end):SetImage("icon16/user_delete.png")
                        end
                end
                context:AddOption ("Выдать лицензию", function() RunConsoleCommand ("darkrp", "givelicense") end):SetImage("icon16/page_add.png")
				context:AddSpacer()context:AddSpacer()
				context:AddOption ("Проверить человека в БД", function() RunConsoleCommand("checkdb") RunConsoleCommand("say", "/me синхронизируется с базой данных") end):SetImage("icon16/coins_add.png")
				context:AddSpacer()context:AddSpacer()


 end
        context:AddSpacer()context:AddSpacer()


context:AddOption ("Кинуть кубик", function() RunConsoleCommand ("say", "/roll 6") end):SetImage("icon16/sport_8ball.png")

                context:AddOption ("Передать деньги тому на кого вы смотрите", function ()
                        draw_textbox("Введите кол-во", "Передать", "", function(a) RunConsoleCommand ("darkrp", "give", tostring(a)) end)
                end):SetImage ("icon16/money.png")

        context:AddOption( "Выбросить оружие", function() RunConsoleCommand ("darkrp", "dropweapon") end ):SetImage("icon16/gun.png")
        context:AddOption( "Выбросить деньги", function()
                draw_textbox("Введите кол-во", "Выбросить", "", function(a) RunConsoleCommand ("darkrp", "dropmoney", tostring(a)) end)


context:AddSpacer()
if ply:IsAdmin() then
context:AddOption ("Логи", function() RunConsoleCommand ("say", "!logs") end):SetImage("icon16/application_osx_terminal.png")
             end
        context:Open()
        context:CenterHorizontal()
        context.y = ScrH() + 100
        context:MoveTo(context.x, ScrH() - context:GetTall() - 8, .0, 0)
end

concommand.Add("open_context_menu", OpenContextMenu)
